apiVersion: apps/v1
kind: Deployment
metadata:
  name: repairbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repairbot
  template:
    metadata:
      labels:
        app: repairbot
    spec:
      containers:
      - name: repairbot
        imagePullPolicy: Always
        image: bradygaster/repairbot:latest
        resources:
          limits:
            cpu: 250m
            memory: 256Mi