apiVersion: apps/v1
kind: Deployment
metadata:
  name: chargebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chargebot
  template:
    metadata:
      labels:
        app: chargebot
    spec:
      containers:
      - name: chargebot
        imagePullPolicy: Always
        image: bradygaster/chargebot:latest
        resources:
          limits:
            cpu: 250m
            memory: 256Mi