apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitorbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitorbot
  template:
    metadata:
      labels:
        app: monitorbot
    spec:
      containers:
      - name: monitorbot
        imagePullPolicy: Always
        image: bradygaster/monitorbot:latest
        resources:
          limits:
            cpu: 250m
            memory: 256Mi